config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :tasks

  root to: "sessions#home"

  resources :users do
    resources :reviews
  end

  resources :items do
    resources :reservations do
      resource :dialogs, shallow: true
    end
  end

resources :tasks, only: [:index, :new, :create, :destroy]

end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @items = Item.where(user_id: current_user.id)
    @reservations = Reservation.where(renter_id: current_user.id)
    @requests = Reservation.where(user_id: current_user.id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/profiles/_editform.html.erb
<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: {class: "form-horizontal form-signin", multipart: true, method: :put}) do |f| %>
  <%= devise_error_messages! %>

  <h2 class="form-signin-heading">Update Your Account</h2>

  <div class="field form-group">
    <%= f.label :username, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :username, class: "form-control", autofocus: true %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :email, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.email_field :email, class: "form-control"  %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :first_name, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :first_name, class: "form-control" %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :last_name, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :birthdate, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.date_field :birthdate, class: "form-control" %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.file_field :avatar, class: "col-sm-4" %>
  </div>

  <div class="field form-group">
    <%= f.label :location, "Address", class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :location, class: "form-control" %>
    </div>
  </div>


  <div class="field form-group">
    <%= f.label :current_password, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.password_field:current_password, autocomplete: "off", class: "form-control" %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :password, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %>
      <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :password_confirmation, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Update", class: "btn btn-success btn-lg btn-block" %>
    </div>
  </div>

  <h3>Cancel my account</h3>

  <p>Unhappy? <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

<% end %>

app/views/profiles/show.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title></title>
       <%= stylesheet_link_tag 'profiles' %>
      </head>
<body>
  <div class="container" id="nav">
    <div class="row">
        <div class="tabs-left text-center">
          <ul class="nav nav-tabs">
            <li class="active"><a href="#a" data-toggle="tab"><p>Gear</p></a></li>
            <li><a href="#b" data-toggle="tab"><p>Requests</p></a></li>
            <li><a href="#c" data-toggle="tab"><p >Reserved</p></a></li>
            <li><a href="#d" data-toggle="tab"><p >Account</p></a></li>
          </ul>
            <div class="tab-content">
              <p id="token"><span class="glyphicon glyphicon-tree-conifer"></span>x<%=current_user.tokens%></p>
              <div class="tab-pane active" id="a">
                <ul class="list-group pull-left text-center">
                <h4>My Available Gear</h4>
                <% @items.each_slice(3) do |items| %>
                  <div class="row">
                  <% items.each do |item| %>
                    <div class="col-md-4">
                    <li class="list-group-item">
                      <% if item.approved %>
                          <% else %>
                            <div class="card" id="profile-card">
                              <img class="card-img-top" src=<%= link_to image_tag(item.image.url(:large)),item.image.url %>
                                <div class="card-block cb">
                                  <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalView-<%=item.id%>">View</button>
                                  <a> <%= link_to 'Delete', item_path(item), class: "btn btn-default btn-xs",
                                                   method: :delete,
                                                   data: {confirm: 'Are you sure?'}%> </a>
                              </div>
                            </div>
                          <% end %>
                        </li>
                      </div>
                      <!-- Modal View -->
                        <div id ="modalView-<%=item.id %>" class="modal fade" role="dialog">
                          <div class="modal-dialog">
                          <!--Modal View content -->
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title"> <%= image_tag(item.image.url(:large))%> </h4>
                              </div>
                              <div class="modal-body">
                                <p><%= item.description %></p>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-default btn-xs" data-dismiss="modal"> Close</button>
                              </div>
                            </div>
                        </div> <!-- Modal Dialog -->
                      </div> <!-- myModal -->
                    <% end %>
                  </div>
                <% end %>
                </ul>
              </div>
              <div class="tab-pane" id="b">
                <ul class="list-group pull-left text-center">
                    <h4>Gear You Have Requested</h4>
                    <% @reservations.each_slice(3) do |reservations| %>
                      <div class="row">
                      <% reservations.each do |res| %>
                        <div class="col-md-4"
                          <li class="list-group-item"
                          <div class="card">
                            <img class="card-img-top" src=<%= link_to image_tag(res.item.image.url(:large)), res.item.image.url %>
                              <div class="card-block cb">
                                <a> <%= link_to 'conversation', "/items/#{res.item.id}/reservations/#{res.id}", class: "btn btn-default btn-xs"  %> </a>
                                  <% if res.item.approved %>
                                     <a> approved </a>
                                  <% else %>
                                    <a> pending... </a>
                                  <% end %>
                               </div>
                              </div>
                          <% end %>
                     </li>
                  </div>
                    <% end %>
                </ul>
              </div>
              <div class="tab-pane" id="c">
                <ul class="list-group pull-left text-center">
                <h4>Your Gear That Has Been Requested</h4>
                  <% @requests.each_slice(3) do |requests| %>
                    <div class="row">
                    <% requests.each do |req| %>
                      <div class="col-md-4"
                      <li class="list-group-item"
                        <div class="card">
                          <img class="card-img-top" src=<%= link_to image_tag(req.item.image.url(:large)), req.item.image.url, :default_url => "missing_:firepit.png"%>
                          <div class="card-block cb">
                            <td> <%= link_to 'conversation', "/items/#{req.item.id}/reservations/#{req.id}", class: "btn btn-default btn-xs"  %> </td>
                             <% if req.item.approved %>
                               <td> approved </td>
                               <td><%= link_to "returned?", item_path(req.item), class: "btn btn-info btn-xs",
                                        method: :put,
                                        data: {confirm: 'Are you sure?' }%> </td>
                             <% else %>
                               <td><%= link_to "approve?", item_path(req.item), class: "btn btn-info btn-xs",
                                        method: :put,
                                        data: {confirm: 'Are you sure?' }%> </td>
                                <td><%= link_to "deny?", item_path(req.item), class: "btn btn-info btn-xs",
                                        method: :put,
                                        data: {confirm: 'Are you sure?' }%> </td>
                             <% end %>
                          </div>
                        </div>
                        <% end %>
                        </li>
                      </div>
                      <% end %>
                   </ul>
                </div>
               <div class="tab-pane" id="d">
                <ul class="list-group pull-left text-center">
                      <li class="list-group-item"
                        <div class="card">
                          <div class="card-block cb">
                            <%= render 'editform' %>
                          </div>
                        </div>
                      </li>
                  </ul>
                </div>
              </div><!-- /tab-content -->
            </div>
          </div><!-- /col -->
        </div><!-- /row -->
      </div><!-- /container -->
    </div>
  </body>
</html>