config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :tasks

  root to: "sessions#home"

  resources :users do
    resources :reviews
  end

  resources :items do
    resources :reservations do
      resource :dialogs, shallow: true
    end
  end

resources :tasks, only: [:index, :new, :create, :destroy]

end

app/models/user.rb
class User < ApplicationRecord
  has_many :reservations
  has_many :items
  has_many :rented_items, {:class_name => "Item", :foreign_key => "renter_id"}

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" },
  :default_url => "tent-icon.jpg"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  has_many :reviews
  has_many :tasks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :location, presence: true
  geocoded_by :location
  after_validation :geocode

  def average_rating
    if reviews.count == 0
      0
    else
      reviews.sum(:rating)/reviews.count
    end
  end

  def self.search(search)
      where("first_name ILIKE ? OR last_name ILIKE ? OR username ILIKE? OR location ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  skip_before_action :require_login, only: [:new, :create]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameteres, only: [:create]
  skip_before_action :verify_authenticity_token, only: :create
  skip_before_action :require_login, only: [:new, :create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index]

  ## GET all staff
  def index
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order("created_at DESC")
    end
  end

## GET new user member form
  def new
    @user = User.new
  end

## POST newly created user member
  def create
    @user = User.create(params[:user])
    # redirect_to
  end

## GET a specific user member
  def show
    @user = User.find(params[:id])
    @items = Item.where(user_id: @user.id)
    @reviews = Review.where(user_id: @user.id)
  end

## GET a form for editing the user member
  def edit
    @user = User.find(params[:id])
  end

## PUT any edits made to the user member
  def update
    @user = User.update(params[:user])
  end

## Delete a user member from the database
  def delete
    @user = User.find(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>List Item</title>
</head>
<body>

<%= form_tag(users_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search By User" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>


<% @users.each do |user| %>

  <%= link_to "#{user.username}", user_path(user),  class:"btn btn-default btn-xs", style: "width: auto" %><%=" has "%><%= user.items.count %><%=" items available"%><br>
  <%= " is miles away" %><br>

<% end %><br>
<%= link_to users_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> All Users
<% end %>

</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

  <h1>  <%= link_to image_tag(@user.avatar.url(:thumb)), @user.avatar.url %> <%=@user.first_name%>
    <% @user.average_rating.times do %>
    <%= image_tag 'firepit.png', size: "30x30", :title => 'fire_pit' %>
    <% end %>
  </h1>

  <h1> <%=@user.first_name%>'s available items: </h1>
  <div class="container">
    <% @items.each_slice(3) do |items| %>
    <div class="row text-center">
      <% items.each do |item| %>
      <div class="col-md-4"
        <div class="card">
         <img class="card-img-top" src=<%= link_to image_tag(item.image.url(:large)), item.image.url %>
        <div class="card-block cb">
          <a> <%= link_to 'Reserve', new_item_reservation_path(item), class: "btn btn-default btn-xs" %> </a>
          <a> <%= link_to 'View', item_path(item), class: "btn btn-default btn-xs" %>  </a>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>

  <h1> <%=@user.first_name %>'s reviews: <a><%= link_to 'Leave a Review', new_user_review_path(@user), class: "btn btn-default btn-xs" %></a></h1>
  <% @reviews.each_slice(3) do |reviews| %>
  <div class="row">
    <% @reviews.each do |review| %>
    <div class="col-md-4"
    <div class="card">
      <div class="row">
        <div class="col-md-4">
          <%= link_to image_tag(review.reviewer.avatar.url(:thumb)), user_path(review.reviewer) %>
        </div>
        <div class="col-md-8">
          <div class="card-block cb">
            <h4 class="ct"> <%= review.reviewer.username %>  <% review.rating.times do  |review| %>
              <%= image_tag 'firepit.png', size: "30x30", :title => 'fire_pit' %> <% end %>
            </h4>
            <%= review.body %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>