config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :tasks

  root to: "sessions#home"

  resources :users do
    resources :reviews
  end

  resources :items do
    resources :reservations do
      resource :dialogs, shallow: true
    end
  end

resources :tasks, only: [:index, :new, :create, :destroy]

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :item
  belongs_to :renter, {:class_name => "User", :foreign_key => :renter_id}

  has_many :dialogs

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def show
    @item = Item.find(params[:item_id])
    @reservation = Reservation.find(params[:id])
    @dialogs = Dialog.where(reservation_id: @reservation.id)
  end

  def new
    @item = Item.find(params[:item_id])
    @reservation = Reservation.new
  end

  def create
    @item = Item.find(params[:item_id])
    @reservation = Reservation.new(res_params)
    @reservation.item_id = @item.id
    @reservation.renter_id = current_user.id
    @reservation.user_id = @item.user.id
    @user = User.find(@item.user.id)

    if @reservation.save
      ReservationMailer.new_reservation_email(@user, @item).deliver_now
      redirect_to "/items/#{@item.id}/reservations/#{@reservation.id}"
    else
      render 'new'
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(res_params)
      redirect_to @reservation
    else
      render 'edit'
    end
  end

  def destroy
    @reservation = reservation.find(params[:id])
    if @reservation.destroy
      redirect_to reservations_path
    else
      redirect_to reservation_path
    end
  end

  private

  def res_params
    params.require(:reservation).permit(:day, :city, :message)
  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_dialog.html.erb
<%= form_with scope: :dialog, url: "/items/#{@item.id}/reservations/#{@reservation.id}/dialogs", class: "form-inline", local: true do |form| %>
  <div class="field form-group">
    <%= form.label :body, "Message:" %>
    <%= form.text_field :body, class: "form-control" %>
  </div>
  <div class="actions form-group">
    <%= form.submit "Post", class: "btn btn-xs" %>
  </div>
<% end %>

app/views/reservations/_form.html.erb
<%= form_with scope: :reservation, url: "/items/#{@item.id}/reservations", local: true do |form| %>

<div class="field form-group">
  <%= form.label :day, class:'col-sm-4 control-label ' %>
    <div class="col-sm-8">
      <%= form.text_field :day, class: 'form-control' %>
    </div>
</div>

<div class="field form-group">
  <%= form.label :city, class: 'col-sm-4 control-label' %>
  <div class="col-sm-8">
    <%= form.text_field :city, class: 'form-control'  %>
  </div>
</div>


<div class="field form-group">
  <%= form.label :message, class: 'col-sm-4 control-label' %>
  <div class="col-sm-10">
    <%= form.text_field :message, class: 'form-control' %>
  </div>
</div>


<div class="actions form-group">
  <div class="col-sm-offset-2 col-sm-10">
  <%= form.submit %>
  </div>
</div>


<% end %>

app/views/reservations/edit.html.erb
Edit

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/reservations/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<table>
  <tr>
    <th>Name </th>
    <th>Description </th>
  </tr>
<% @reservations.each do |reservation| %>
  <tr>
    <td> <%= reservation.name  %></td>
    <td> <%= reservation.description  %></td>
    <td> <%= link_to 'Show', reservation_path(reservation) %> </td>
    <td> <%= link_to 'Edit', edit_reservation_path(reservation) %> </td>
    <td> <%= link_to 'Delete', reservation_path(reservation),
              method: :delete,
              data: {confirm: 'Are you sure?' } %> </td>
  </tr>
<% end %>
</table>

  <p> <%= link_to 'New', new_reservation_path %> </p>
</body>
</html>

app/views/reservations/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<%= render 'form' %>
<%= link_to 'Back', items_path %>
</body>
</html>

app/views/reservations/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

<div class="reservation-wrapper">
  <h2><%= @item.name %></h2>

  <ul class="reservation-details col-sm-9">
    <li class="reservation-detail-item"><span class="item-detail">Description:</span><%= @item.description %></li>
    <li class="reservation-detail-item"><span class="item-detail">Date:</span><%= @reservation.day %></li>
    <li class="reservation-detail-item"><span class="item-detail">Username:</span><%= @item.user.username %></li>
    <li class="reservation-detail-item"><span class="item-detail">Requester Location:</span><%= @reservation.city %></li>
    <li class="reservation-detail-item"><span class="item-detail">Note:</span><%= @reservation.message %> </li>
  </ul>

   <% @dialogs.each do |dialog| %>
    <% if (current_user.id == dialog.user_id) || (current_user.id == dialog.renter_id) %>
      <div class="container-dialog col-sm-9">
        <span class="dialog-author"><%= dialog.username %>:</span>
        <p>"<%= dialog.body %>"</p>
        <span class="timestamp"><%= dialog.updated_at %></span>
      </div>
    <% else %>
      <div class="container-dialog darker col-sm-9">
        <span class="dialog-author"><%= dialog.username %>:</span>
        <p>"<%= dialog.body %>"</p>
        <span class="timestamp"><%= dialog.updated_at %></span>
      </div>
    <% end %>
  <% end %>

  <div class="form-group">
      <%= render 'dialog' %>
      <%= link_to 'Back', profile_path(current_user.id) %>
  </div>
</div>

</body>
</html>