config/routes.rb
Rails.application.routes.draw do
  resources :profiles

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  resources :tasks

  root to: "sessions#home"

  resources :users do
    resources :reviews
  end

  resources :items do
    resources :reservations do
      resource :dialogs, shallow: true
    end
  end

resources :tasks, only: [:index, :new, :create, :destroy]

end

app/models/item.rb
class Item < ApplicationRecord

  has_attached_file :image, styles: {small: "64x64", med: "100x100", large: "200x200#"},
  :default_url => "pit_default.png"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  belongs_to :user

  has_many :reservations

  def self.search(search)
      where("name ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%")
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :require_login, only: [:show, :index]
  respond_to :html, :js

  def index
    if params[:search]
      @items = Item.search(params[:search]).order("created_at DESC")
    else
      @items = Item.all.order("created_at DESC").includes(:user)
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
   @item = Item.new(item_params)
   @item.user_id = current_user.id

    if @item.save
      redirect_to profile_path(current_user.id)
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @reservation = Reservation.find_by(item_id: @item.id)
    @renter = User.find_by(id: @reservation.renter_id)

    if @item.approved
      @item.update(approved: false)
      up_tokens = @item.user.tokens += 1
      @item.user.update(tokens: up_tokens)
      down_tokens = @renter.tokens -= 1
      @renter.update(tokens: down_tokens)

      @reservation.destroy
      redirect_to profile_path(current_user.id)
    else
      @item.update(approved: true)
      redirect_to profile_path(current_user.id)
    end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.reservations.destroy_all && @item.destroy
      redirect_to profile_path(current_user.id)
    else
      redirect_to profile_path(current_user.id)
    end
  end

  private
  def item_params
    params.require(:item).permit(:name, :description, :image)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
  def resource_item
    :item
  end

  def res
    @item ||= Item.new
  end

  def resource_reservation
    :reservation
  end

  def reservation
    @reservatopm ||= Reservation.new
  end

  def create

  end
end

app/views/items/_edit.html.erb
<%= form_for(@item, html: {class: 'form-horizontal'}, html: {multipart: true}) do |f|%>
  <div class="field form-group">
    <%= f.label :approved, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :approved, class: 'form-control' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/items/_form.html.erb
<%= form_for(@item, html: {multipart: true, class: 'form-horizontal form-signin', style: 'width: 300px;'}) do |f|%>

  <h2 class="form-signin-heading">List an item to share</h2>

  <div class="field form-group">
    <%= f.label :name, class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :description, class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :image_file_name, "Image", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-success btn-lg btn-block" %>
    </div>
  </div>
<% end %>

app/views/items/_formr.html.erb
<%= form_for(reservation, as: resource_reservation, url: item_reservations_path(resource_item), html: {multipart: true, class: 'form-horizontal form-signin'}) do |f|%>

  <h2 class="form-signin-heading">Reserve item</h2>

  <div class="field form-group">
    <%= f.label :day, class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :day, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :city, class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_area :city, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :message, class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_area :message, class: 'form-control' %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-success btn-lg btn-block" %>
    </div>
  </div>
<% end %>

app/views/items/_formt.html.erb
<%= form_for(res, as: resource_item, url: items_path(resource_item), html: {multipart: true, class: 'form-horizontal form-signin', style: 'width: 300px;'}) do |f|%>

  <h2 class="form-signin-heading">List an item to share</h2>

  <div class="field form-group">
    <%= f.label :name, class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :description, class: 'col-sm-3 control-label' %>
    <div class="col-sm-9">
      <%= f.text_area :description, class: 'form-control' %>
    </div>
  </div>

  <div class="field form-group">
    <%= f.label :image_file_name, "Image", class: "col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.file_field :image %>
    </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-success btn-lg btn-block" %>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

<%= render 'edit' %>

<%= link_to 'Back', profile_path(current_user.id) %>

</body>
</html>

app/views/items/index.html.erb
  <!DOCTYPE html>
    <html>
      <head>
       <title></title>
          <%= stylesheet_link_tag 'profiles' %>
      </head>
<body>
  <div class="container" id ="nav">
    <div class="row">
      <div class="tabs-left text-center">
        <ul class="nav nav-tabs">
          <li class="active"> <a href="#a" data-toggle="tab" class="btn btn-warning">Available Gear</a></li>
          <li><a href="#b" data-toggle="tab" class="btn btn-warning">Post New Item</a></li>
        </ul>
        </div>
            <div class="tab-content">
              <div class="tab-pane active" id="a">
                <ul class="list-group pull-left text-center">
                  <% if @items.blank? %>
                    <h4>There is no gear containing the term <%= params[:search] %>.</h4>
                  <% end %>
                  <% @items.each_slice(3) do |item_group| %>
                    <div class="row">
                      <% item_group.each do |item| %>
                        <div class="col-md-4">
                        <li class="list-group-item">
                        <% if item.approved%>
                        <% else %>
                            <div class="card" id="profile-card">
                              <img class="card-img-top" src=<%= link_to image_tag(item.image.url(:large)), item.image.url %>
                              <div class="card-block cb">
                                <p><%= "Posted: "%><%= item.created_at.strftime("%A, %b %d") %></p>
                                <a> <%= link_to image_tag("More-Info-Button.png", size: '100x40'), item_path(item), class: "show-item-button"%> </a>
                              <div class="append-show"><b><%="Description: "%></b><%= item.description %><br>
                                <iframe width="200" height="200" frameborder="0" style="border:0"
                                  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBnrDAazGk_GCygyfvQb_xSFfEMhdT2ZK8&q=<%= item.user.location %>" allowfullscreen></iframe><br>
                                  <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalReserve-<%=item.id%>">Reserve</button>
                                  <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalOwner-<%=item.id%>">Owner</button>
                                   <button type="button" class="btn btn-default btn-xs" data-toggle="modal" data-target="#modalView-<%=item.id%>">View</button>  </div>
                                </div>
                              </div>
                          <% end %>
                        </li>
                      </div>
                        <!-- Modal Owner -->
                        <div id ="modalOwner-<%=item.id %>" class="modal fade" role="dialog">
                          <div class="modal-dialog">
                        <!--Modal Owner content -->
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title"><%= image_tag(item.user.avatar.url(:thumb))%> <%=item.user.username %> <% item.user.average_rating.times do %>
                                  <%= image_tag 'firepit.png', size: "30x30", :title => 'fire_pit' %>
                                  <% end %>
                                  <a><%= link_to 'Leave a Review', new_user_review_path(item.user), class: "btn btn-default btn-xs" %></a>
                               </h4>
                              </div>
                              <div class="modal-body">
                                <% item.user.reviews.each do |review| %>
                                  <h4 class="ct"> <%= review.reviewer.username %>
                                    <% review.rating.times do |review| %>
                                    <%= image_tag 'firepit.png', size: "30x30", :title => 'fire_pit' %>
                                    <% end %>
                                    <%=review.body%>
                                  </h4>
                                 <% end %>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-default btn-xs" data-dismiss="modal"> Close</button>
                              </div>
                            </div>
                          </div> <!-- Modal Dialog -->
                        </div> <!-- myModal -->
                      <!-- Modal Reserve -->
                        <div id ="modalReserve-<%=item.id%>" class="modal fade" role="dialog">
                          <div class="modal-dialog">
                        <!--Modal Reserve content -->
                            <div class="modal-content">
                              <div class="modal-body">
                                <%= form_for(reservation, as: resource_reservation, url: item_reservations_path(item.id), html: {multipart: true, class: 'form-horizontal form-signin'}) do |f|%>
                                      <h2 class="form-signin-heading">Reserve item</h2>
                                      <div class="field form-group">
                                        <%= f.label :day, class: 'col-sm-3 control-label' %>
                                        <div class="col-sm-9">
                                          <%= f.text_field :day, class: 'form-control' %>
                                        </div>
                                      </div>
                                      <div class="field form-group">
                                        <%= f.label :city, class: 'col-sm-3 control-label' %>
                                        <div class="col-sm-9">
                                          <%= f.text_area :city, class: 'form-control' %>
                                        </div>
                                      </div>
                                      <div class="field form-group">
                                        <%= f.label :message, class: 'col-sm-3 control-label' %>
                                        <div class="col-sm-9">
                                          <%= f.text_area :message, class: 'form-control' %>
                                        </div>
                                      </div>
                                        <div class="actions form-group">
                                          <div class="col-sm-offset-2 col-sm-10">
                                            <%= f.submit "Request Reservation", class: "btn btn-success btn-lg btn-block" %>
                                          </div>
                                        </div>
                                      <% end %>
                                      </div>
                                      <div class="modal-footer">
                                        <button type="button" class="btn btn-default btn-xs" data-dismiss="modal"> Close</button>
                                      </div>
                                    </div>
                                  </div> <!-- Modal Dialog -->
                                </div> <!-- myModal -->
                                <!-- Modal View -->
                                  <div id ="modalView-<%=item.id %>" class="modal fade" role="dialog">
                                    <div class="modal-dialog">
                                  <!--Modal View content -->
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <button type="button" class="close" data-dismiss="modal">&times;</button>
                                          <h4 class="modal-title"> <%= image_tag(item.image.url(:large))%> </h4>
                                        </div>
                                        <div class="modal-body">
                                          <p><%= item.description %></p>
                                        </div>
                                        <div class="modal-footer">
                                          <button type="button" class="btn btn-default btn-xs" data-dismiss="modal"> Close</button>
                                        </div>
                                      </div>
                                    </div> <!-- Modal Dialog -->
                                  </div> <!-- myModal -->
                              <% end %>
                            </div>
                          <% end %>
                        </ul>
            </div>
              <div class="tab-pane" id="b">
                <ul class="list-group pull-left text-center">
                  <li class="list-group-item"
                    <div class="card">
                      <div class="card-block cb">
                        <%= render 'formt' %>
                      </div>
                    </div>
                  </li>
                </ul>
              </div>
            </div><!-- /tab-content -->
          </div><!-- /row -->
        </div><!-- /container -->
      </div>
</body>
</html>

app/views/items/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>

<%= render 'form' %>

<%#= link_to 'Back' , profile_path(current_user.id) %>

</body>
</html>

app/views/items/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<h1><%= @item.name%></h1>
<div class="item-links">
  <%= link_to new_item_path, class: 'btn btn-warning' do %>
    <i></i> Post New Item
  <% end %>
  <%= link_to profile_path(current_user.id), class: 'btn btn-warning' do %>
    <i></i> Back to Profile
  <% end %>
  <%= link_to items_path, class: 'btn btn-warning' do %>
    <i></i> List All Items
  <% end %>
</div>

<center>
<div class ="col-md-offset-3">
  <%= image_tag(@item.image.url, :size => "auto", class: "image-item-show") %>
</div>
</center>

<div class="item-show-footer">
  <h3><%= @item.description %></h3>

<div class="owner">
  <% if user_signed_in? %>
    <h4><%= "Owner is "%><%= current_user.distance_to(@item.user.location).round(2) %><%= " miles away" %></h4><br>
  <% end %>
</div>

  <%= link_to 'Reserve', new_item_reservation_path(@item), class: "btn btn-default btn-xs" %>
</div>
</body>
</html>